"""
patch_script_js_map.py
======================
Updates script.js to:
  1. Remove volumesDb (hardcoded volumes) — use city.y2_clients from city_data.json
  2. Replace the forEach string-parsing block with direct field reads (all raw_ fields)
  3. Update the renderMapMarkers marker loop to use pre-computed payback_raw,
     pat_ratio_raw, opex_raw, capex_mid, underserved_raw, coords from city_data.json
"""
import re, os

WORKDIR = r"c:\Users\vince\Projects\HairSpa\Oasis_Salon_Web"
JS_FILE = os.path.join(WORKDIR, "script.js")

with open(JS_FILE, "r", encoding="utf-8") as f:
    content = f.read()

# ── 1. Remove volumesDb hardcoded block ───────────────────────────────────────
vol_start = content.find("const volumesDb")
vol_end   = content.find("};", vol_start) + 2
# skip trailing semicolons
while vol_end < len(content) and content[vol_end] == ";":
    vol_end += 1

old_vdb = content[vol_start:vol_end]
new_vdb = (
    "// volumesDb removed — city.y2_clients now comes directly from city_data.json\n"
    "    // (generated by excel_to_json.py from salon_data.xlsx)\n"
)
content = content.replace(old_vdb, new_vdb, 1)
print("✓ Removed volumesDb hardcoded block")

# ── 2. Replace the forEach string-parse block with direct raw field reads ──────
OLD_FOREACH = '''citiesDb.forEach(city => {
        const key = city.url.replace('.html', '');
        city.volume = volumesDb[key] || 300;
        
        // ticketVal
        if (city.ticket) {
            city.ticketVal = parseInt(city.ticket.replace(/[^0-9]/g, '')) || 0;
        } else {
            city.ticketVal = 0;
        }
        
        // opexVal
        if (city.opex) {
            city.opexVal = parseInt(city.opex.replace(/[^0-9]/g, '')) || 0;
        } else {
            city.opexVal = 0;
        }
        
        // capexVal
        if (city.capex) {
            const capexMatches = city.capex.match(/(\\d+)k/g);
            if (capexMatches) {
                const nums = capexMatches.map(m => parseInt(m) * 1000);
                city.capexVal = nums.reduce((a, b) => a + b, 0) / nums.length;
            } else {
                city.capexVal = parseInt(city.capex.replace(/[^0-9]/g, '')) || 0;
            }
        } else {
            city.capexVal = 0;
        }
        
        // taxVal
        if (city.tax) {
            city.taxVal = (parseFloat(city.tax.replace(/[^0-9.]/g, '')) || 0) / 100;
        } else {
            city.taxVal = 0;
        }
    });'''

NEW_FOREACH = '''// Map city_data.json raw fields to the aliases used by renderMapMarkers
        // and other dashboard functions. All values now come from Excel via city_data.json.
        citiesDb.forEach(city => {
            // Numeric aliases (used by legacy rendering functions)
            city.ticketVal  = city.ticket_raw   || 0;   // USD integer
            city.opexVal    = city.opex_raw      || 0;   // USD/month
            city.capexVal   = city.capex_mid     || 0;   // USD midpoint
            city.taxVal     = city.tax_raw       || 0;   // e.g. 0.20
            city.volume     = city.y2_clients    || 300; // sessions/month at 75% util
        });'''

if OLD_FOREACH in content:
    content = content.replace(OLD_FOREACH, NEW_FOREACH, 1)
    print("✓ Replaced forEach string-parse block with direct raw field reads")
else:
    # Try a more flexible match
    pat = re.compile(r'citiesDb\.forEach\(city =>\s*\{.*?city\.taxVal.*?\}\s*\}\);', re.DOTALL)
    content, n = pat.subn(NEW_FOREACH, content, count=1)
    if n:
        print("✓ Replaced forEach block (regex fallback)")
    else:
        print("⚠ Could not find forEach parse block — check manually")

# ── 3. Update renderMapMarkers marker loop to use pre-computed fields ──────────
OLD_MARKER_LOOP = '''// Render markers
        citiesDb.forEach(city => {
            const ticketVal = city.ticketVal;
            const opexVal = city.opexVal;
            const capexVal = city.capexVal;
            const volumeBase = city.volume;
            const taxRate = city.taxVal;

            const cogsVal = ticketVal * 0.10;
            const contribMargin = ticketVal - cogsVal;
            const monthlyBreakeven = Math.round(opexVal / contribMargin);

            const preTaxPAT = (volumeBase * contribMargin) - opexVal;
            const taxVal = preTaxPAT > 0 ? preTaxPAT * taxRate : 0;
            const pat = preTaxPAT - taxVal;
            const ratio = Math.round((pat / opexVal) * 100);
            const payback = pat > 0 ? Math.round(capexVal / pat) : 0;

            const color = getColor(payback);
            const opacity = getOpacity(capexVal);
            const radius = getRadius(city.underserved);

            const formatStr = city.format;
            const capexStr = city.capex;
            const opexStr = city.opex;
            const paybackStr = payback > 0 ? `${payback} Months` : "N/A";
            const ratioStr = `${ratio}% (Post-Tax)`;'''

NEW_MARKER_LOOP = '''// Render markers — all values from city_data.json (Excel-driven, no recomputation)
        citiesDb.forEach(city => {
            // Use pre-computed values from Excel model (via city_data.json)
            const payback = city.payback_raw   || 0;   // months at 75% util
            const ratio   = city.pat_ratio_raw || 0;   // % PAT/OPEX
            const capexVal= city.capex_mid     || 0;   // USD midpoint for opacity scale

            const color   = getColor(payback);
            const opacity = getOpacity(capexVal);
            const radius  = getRadius(city.underserved);  // "65%" string → parsed in getRadius

            const formatStr  = city.format;
            const capexStr   = city.capex;
            const opexStr    = city.opex;
            const paybackStr = payback > 0 ? `${payback} Months` : "N/A";
            const ratioStr   = `${ratio}% (Post-Tax)`;'''

if OLD_MARKER_LOOP in content:
    content = content.replace(OLD_MARKER_LOOP, NEW_MARKER_LOOP, 1)
    print("✓ Updated map marker loop to use pre-computed Excel fields")
else:
    # Flexible regex match
    pat = re.compile(
        r'// Render markers\s*\n\s*citiesDb\.forEach\(city =>\s*\{.*?const ratioStr.*?;',
        re.DOTALL
    )
    content, n = pat.subn(NEW_MARKER_LOOP, content, count=1)
    if n:
        print("✓ Updated marker loop (regex fallback)")
    else:
        print("⚠ Could not find marker loop — check manually")

# ── 4. Fix the fitBounds call — city.coords is now [lat, lon] from JSON ────────
# Ensure it still works (it should, since coords is now an array in the JSON)
if 'citiesDb.map(city => city.coords)' in content:
    print("✓ fitBounds uses city.coords — already correct (array from JSON)")

# ── 5. Fix updateSubpageContent — it recomputes breakeven/payback from raw vals
# Update it to use pre-computed fields instead
OLD_SUBPAGE = '''// Parameters
        const ticketVal = city.ticketVal;
        const opexVal = city.opexVal;
        const capexVal = city.capexVal;
        const volumeBase = city.volume;
        const taxRate = city.taxVal;

        const cogsVal = ticketVal * 0.10;
        const contribMargin = ticketVal - cogsVal;
        const monthlyBreakeven = Math.round(opexVal / contribMargin);
        const dailyBreakeven = Math.round(monthlyBreakeven / 30);'''

NEW_SUBPAGE = '''// Parameters — all from city_data.json (Excel-driven)
        const ticketVal        = city.ticket_raw        || 0;
        const opexVal          = city.opex_raw          || 0;
        const capexVal         = city.capex_mid         || 0;
        const volumeBase       = city.y2_clients        || 300;
        const taxRate          = city.tax_raw           || 0;
        const monthlyBreakeven = city.breakeven_raw     || 0;
        const dailyBreakeven   = city.be_daily ? parseFloat(city.daily_breakeven) : Math.round(monthlyBreakeven / 30);'''

if OLD_SUBPAGE in content:
    content = content.replace(OLD_SUBPAGE, NEW_SUBPAGE, 1)
    print("✓ Updated updateSubpageContent to use raw fields")
else:
    print("⚠ updateSubpageContent block not found exactly — check manually")

# ── Write ──────────────────────────────────────────────────────────────────────
with open(JS_FILE, "w", encoding="utf-8") as f:
    f.write(content)

print(f"\n✅ script.js updated: {len(content):,} chars")
print("   Map now reads coords/underserved/payback/pat_ratio from city_data.json")
