"""
patch_script_js.py
==================
Replaces the hardcoded citiesDb block in script.js with a fetch() call
that loads city_data.json at runtime.

All rendering functions are wrapped in initDashboard() which is called
after the JSON loads. This is a one-time migration — run once.
"""
import re, os

WORKDIR = r"c:\Users\vince\Projects\HairSpa\Oasis_Salon_Web"
JS_FILE = os.path.join(WORKDIR, "script.js")

with open(JS_FILE, "r", encoding="utf-8") as f:
    content = f.read()

# ── 1. Find and remove the hardcoded citiesDb block ───────────────────────────
start = content.find("const citiesDb")
depth = 0
i = content.find("[", start)
for j in range(i, len(content)):
    if content[j] == "[":  depth += 1
    elif content[j] == "]":
        depth -= 1
        if depth == 0:
            end_bracket = j
            break
end = end_bracket + 1
while end < len(content) and content[end] in ";": end += 1

print(f"Found citiesDb: chars {start}-{end}, lines ~{content[:start].count(chr(10))+1}-{content[:end].count(chr(10))}")

# ── 2. Build the replacement: let citiesDb = [] + async fetch logic ───────────
FETCH_REPLACEMENT = """let citiesDb = [];  // Populated from city_data.json at runtime

    // ==========================================
    // ASYNC CITY DATA LOADER
    // Reads from city_data.json (generated by excel_to_json.py from salon_data.xlsx)
    // To update: edit salon_data.xlsx → run excel_to_json.py → commit & push
    // ==========================================
    function loadCityDataAndInit() {
        fetch('city_data.json')
            .then(function(response) {
                if (!response.ok) throw new Error('city_data.json not found: ' + response.status);
                return response.json();
            })
            .then(function(rawData) {
                citiesDb = rawData;
                initDashboard();
            })
            .catch(function(err) {
                console.error('[Oasis] Failed to load city_data.json:', err);
                // Graceful fallback: show error state on dashboard
                const main = document.querySelector('main, .dashboard-content, #city-grid');
                if (main) {
                    main.insertAdjacentHTML('afterbegin',
                        '<div style="background:#fee;color:#900;padding:1rem;border-radius:8px;margin:1rem">' +
                        '⚠️ Could not load city_data.json. Run excel_to_json.py and refresh.' +
                        '</div>');
                }
            });
    }"""

content = content[:start] + FETCH_REPLACEMENT + content[end:]
print("  ✓ Replaced citiesDb with fetch() loader")

# ── 3. Find the block that starts processing citiesDb (the forEach block)
#       and everything after it up to the init calls — wrap in initDashboard()
# ─────────────────────────────────────────────────────────────────────────────
# The forEach starts parsing raw values; the rendering calls (renderSidebar,
# updatePlatformComponents) come much later.
# We wrap everything from citiesDb.forEach to the end of the DOMContentLoaded block
# in a new function: function initDashboard() { ... }

# Find citiesDb.forEach start
foreach_start = content.find("citiesDb.forEach(city =>")
print(f"  citiesDb.forEach at char: {foreach_start}")

# Find initMobileNav() call — the first rendering call
init_mobile = content.find("initMobileNav();")
print(f"  initMobileNav() at char: {init_mobile}")

# Find the end of the DOMContentLoaded block by finding the last });
# The DOMContentLoaded listener is: document.addEventListener('DOMContentLoaded', () => { ... });
# Find where loadCityDataAndInit() should be called — right after all function defs,
# just before initMobileNav()
# We want to:
# 1. Wrap [foreach_start ... end of file-minus-last-brace] in initDashboard()
# 2. Replace the inline init calls to use initDashboard as the callback

# Find last occurrence of }); which closes the DOMContentLoaded
# The file ends with the applyFilters function, not inside DOMContentLoaded
# Let's find where the file ends relative to DOMContentLoaded

# Strategy: wrap the forEach + all code through the rendering calls in initDashboard()
# Insert "function initDashboard() {" before the forEach
# Insert closing "}" after the last rendering call block
# Then add loadCityDataAndInit(); right before the first rendering call was

# Find what comes just before initMobileNav
before_init = content[init_mobile - 300 : init_mobile]
print(f"\nCode just before initMobileNav:\n{before_init}")

# ── 4. Insert the initDashboard wrapper ───────────────────────────────────────
INIT_DASH_OPEN = """

    // ==========================================
    // DASHBOARD INITIALIZER (called after city_data.json loads)
    // ==========================================
    function initDashboard() {
        // Parse baseline numerical values from city_data.json fields
        """

# Find the exact insert point: just before "citiesDb.forEach"
insert_at = foreach_start
content = content[:insert_at] + INIT_DASH_OPEN + content[insert_at:]
print("  ✓ Inserted initDashboard() open")

# Now find where to close initDashboard() and call loadCityDataAndInit()
# After reinserting, the positions shifted. Find the init calls again.
init_mobile_new = content.find("initMobileNav();")
init_area = content[init_mobile_new - 100 : init_mobile_new + 600]
print(f"\nCode around initMobileNav (new positions):\n{init_area}")

# Find "handleScrollAnchor();" and the hashchange block — these are the last init calls
# The initDashboard() should close just before the hashchange listener
# OR we include everything through the end of the DOMContentLoaded 
# For simplicity: close initDashboard() right before the last }); of DOMContentLoaded

# Find applyFilters function definition — it's the last one, outside initDashboard
apply_filters_idx = content.rfind("function applyFilters")
print(f"\napplyFilters at: {apply_filters_idx}")
# Find the last }); before applyFilters (closes DOMContentLoaded block or something)

# CLEANER APPROACH: find "window.addEventListener('hashchange'" 
# and close initDashboard() just BEFORE that (but still inside DOMContentLoaded)
hashchange_idx = content.find("window.addEventListener('hashchange'")
print(f"hashchange listener at: {hashchange_idx}")

# Insert closing brace of initDashboard() just before hashchange
INIT_DASH_CLOSE = """
    } // end initDashboard()

    // ── Kick off: load JSON then init ────────────────────────────────────────
    """
content = content[:hashchange_idx] + INIT_DASH_CLOSE + content[hashchange_idx:]
print("  ✓ Inserted initDashboard() close")

# ── 5. Replace the now-obsolete direct init calls ─────────────────────────────
# initMobileNav() and renderSidebar() used to be called inline
# They should still be called inline (they don't need city data)
# updatePlatformComponents() needs citiesDb — it will be called inside initDashboard() via forEach → wait
# Actually, initMobileNav + renderSidebar are called inside initDashboard now (since we wrapped it)
# So we just need to ADD the loadCityDataAndInit() call BEFORE the hashchange listener

# Find the new position of the loadCityDataAndInit call insertion point
insert_call_idx = content.find("} // end initDashboard()")
after_close = content.find("\n", insert_call_idx) + 1
# Insert the call right after the closing comment
call_insert = content.find("// ── Kick off: load JSON then init", insert_call_idx)
after_comment = content.find("\n", call_insert) + 1
content = content[:after_comment] + "    loadCityDataAndInit();\n" + content[after_comment:]
print("  ✓ Added loadCityDataAndInit() call")

# ── 6. Write out ──────────────────────────────────────────────────────────────
with open(JS_FILE, "w", encoding="utf-8") as f:
    f.write(content)

print(f"\n✅ script.js patched successfully")
print(f"   Total size: {len(content):,} chars ({content.count(chr(10)):,} lines)")
print(f"   citiesDb is now fetched from city_data.json at runtime")
